
[functions.send-contact-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-contact-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-contact-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-contact-email/*.html" ]

[functions.send-testimonial-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-testimonial-email/deno.json"
entrypoint = "./functions/send-testimonial-email/index.ts"

[functions.send-maintenance-notification]
enabled = true
verify_jwt = true
import_map = "./functions/send-maintenance-notification/deno.json"
entrypoint = "./functions/send-maintenance-notification/index.ts"

[functions.send-access-approval-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-access-approval-email/deno.json"
entrypoint = "./functions/send-access-approval-email/index.ts"

[functions.notify-admins-new-request]
enabled = true
verify_jwt = false
import_map = "./functions/notify-admins-new-request/deno.json"
entrypoint = "./functions/notify-admins-new-request/index.ts"

[functions.send-admin-invitation]
enabled = true
verify_jwt = true
import_map = "./functions/send-admin-invitation/deno.json"
entrypoint = "./functions/send-admin-invitation/index.ts"


