/* src/admin/services/resumeDownloads.mock.ts */
import { ResumeDownload } from '../types/resumeDownload';

export const MOCK_RESUME_DOWNLOADS: ResumeDownload[] = [
  {
    id: 'rd1',
    dateTime: 'Jan 15, 2024\n10:42 AM',
    visitorName: 'Sarah Johnson',
    visitorEmail: 'sarah.johnson@designstudio.com',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    isKnown: true,
    country: 'United States',
    city: 'New York',
    device: 'Desktop',
    source: 'LinkedIn',
    downloadedFrom: 'Hero Section',
    duration: '8m 22s',
    browser: 'Chrome 120',
    os: 'macOS Sonoma',
    submissionTime: '10:42 AM'
  },
  {
    id: 'rd2',
    dateTime: 'Jan 15, 2024\n09:18 AM',
    visitorName: 'Anonymous Visitor',
    visitorEmail: null,
    avatarUrl: null,
    isKnown: false,
    country: 'Germany',
    city: 'Berlin',
    device: 'Desktop',
    source: 'Google Search',
    downloadedFrom: 'About Page',
    duration: '5m 10s',
    browser: 'Chrome 120',
    os: 'Windows 11',
    submissionTime: '09:18 AM'
  },
  {
    id: 'rd3',
    dateTime: 'Jan 14, 2024\n3:55 PM',
    visitorName: 'Marcus Chen',
    visitorEmail: 'marcus@techcorp.io',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    isKnown: true,
    country: 'Singapore',
    city: 'Singapore',
    device: 'Mobile',
    source: 'GitHub',
    downloadedFrom: 'Projects Page',
    duration: '12m 04s',
    browser: 'Chrome Mobile',
    os: 'Android 14',
    submissionTime: '3:55 PM'
  },
  {
    id: 'rd4',
    dateTime: 'Jan 14, 2024\n11:29 AM',
    visitorName: 'Emma Williams',
    visitorEmail: 'emma.w@creativeagency.co',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    isKnown: true,
    country: 'United Kingdom',
    city: 'London',
    device: 'Desktop',
    source: 'Direct',
    downloadedFrom: 'Home Page',
    duration: '6m 47s',
    browser: 'Safari 17',
    os: 'macOS Sonoma',
    submissionTime: '11:29 AM'
  },
  {
    id: 'rd5',
    dateTime: 'Jan 13, 2024\n7:02 PM',
    visitorName: 'Anonymous Visitor',
    visitorEmail: null,
    avatarUrl: null,
    isKnown: false,
    country: 'Canada',
    city: 'Toronto',
    device: 'Tablet',
    source: 'Direct',
    downloadedFrom: 'About Page',
    duration: '3m 15s',
    browser: 'Safari Mobile',
    os: 'iOS 17',
    submissionTime: '7:02 PM'
  },
  {
    id: 'rd6',
    dateTime: 'Jan 13, 2024\n2:14 PM',
    visitorName: 'David Park',
    visitorEmail: 'd.park@startup.xyz',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    isKnown: true,
    country: 'South Korea',
    city: 'Seoul',
    device: 'Desktop',
    source: 'LinkedIn',
    downloadedFrom: 'Hero Section',
    duration: '9m 38s',
    browser: 'Chrome 120',
    os: 'Windows 11',
    submissionTime: '2:14 PM'
  },
  {
    id: 'rd7',
    dateTime: 'Jan 12, 2024\n5:33 PM',
    visitorName: 'Olivia Martinez',
    visitorEmail: 'olivia@digitalmedia.es',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    isKnown: true,
    country: 'Spain',
    city: 'Madrid',
    device: 'Desktop',
    source: 'Google Search',
    downloadedFrom: 'Projects Page',
    duration: '14m 51s',
    browser: 'Safari 17',
    os: 'macOS Sonoma',
    submissionTime: '5:33 PM'
  },
  {
    id: 'rd8',
    dateTime: 'Jan 12, 2024\n1:47 PM',
    visitorName: 'Anonymous Visitor',
    visitorEmail: null,
    avatarUrl: null,
    isKnown: false,
    country: 'India',
    city: 'Bangalore',
    device: 'Mobile',
    source: 'GitHub',
    downloadedFrom: 'Home Page',
    duration: '2m 09s',
    browser: 'Chrome Mobile',
    os: 'Android 14',
    submissionTime: '1:47 PM'
  },
  {
    id: 'rd9',
    dateTime: 'Jan 11, 2024\n10:05 AM',
    visitorName: 'Lars Andersen',
    visitorEmail: 'lars@nordic.dk',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    isKnown: true,
    country: 'Denmark',
    city: 'Copenhagen',
    device: 'Desktop',
    source: 'Direct',
    downloadedFrom: 'About Page',
    duration: '7m 22s',
    browser: 'Firefox 121',
    os: 'macOS Sonoma',
    submissionTime: '10:05 AM'
  }
];

export const MOCK_SUMMARY = {
  total: 386,
  showingCount: 9
};
