/* src/admin/services/testimonials.mock.ts */
import { Testimonial } from '../types/testimonial';

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Sarah Johnson',
    company: 'Design Studio Co.',
    role: 'Creative Director',
    rating: 5,
    preview: 'Ashok delivered one of the most polished UI systems I have ever worked with. The layouts are modern and highly responsive.',
    country: 'United States',
    date: 'Jan 15, 2024',
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    email: 'sarah.j@designstudio.co',
    city: 'San Francisco',
    submittedFrom: 'Testimonials Page',
    device: 'Desktop',
    browser: 'Chrome 120',
    os: 'macOS Sonoma',
    trafficSource: 'LinkedIn',
    submissionTime: '10:15 AM PST'
  },
  {
    id: 't2',
    name: 'Marcus Chen',
    company: 'TechCorp Inc.',
    role: 'CTO',
    rating: 5,
    preview: 'Outstanding full-stack developer. Delivered our React dashboard on time and above expectations. The code quality, documentation, and attention to detail were all exceptional. Highly recommended for any serious project.',
    country: 'Singapore',
    date: 'Jan 14, 2024',
    status: 'pending',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    email: 'marcus@techcorp.io',
    city: 'Singapore',
    submittedFrom: 'Testimonials Page',
    device: 'Desktop',
    browser: 'Chrome 120',
    os: 'macOS Sonoma',
    trafficSource: 'LinkedIn',
    submissionTime: '2:34 PM SGT'
  },
  {
    id: 't3',
    name: 'Emma Williams',
    company: 'Creative Agency',
    role: 'Head of Product',
    rating: 4,
    preview: 'Excellent communication and strong technical skills throughout the project. Our team is very happy with the final system design.',
    country: 'United Kingdom',
    date: 'Jan 13, 2024',
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    email: 'emma@creativeagency.com',
    city: 'London',
    submittedFrom: 'Testimonials Page',
    device: 'Desktop',
    browser: 'Safari 17',
    os: 'macOS Sonoma',
    trafficSource: 'Twitter',
    submissionTime: '4:12 PM GMT'
  },
  {
    id: 't4',
    name: 'David Park',
    company: 'Startup XYZ',
    role: 'Founder & CEO',
    rating: 5,
    preview: 'We hired Ashok to build our entire analytics platform. The result exceeded all expectations, and the layout looks premium.',
    country: 'South Korea',
    date: 'Jan 12, 2024',
    status: 'remind_later',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    email: 'david@startupxyz.kr',
    city: 'Seoul',
    submittedFrom: 'Testimonials Page',
    device: 'Desktop',
    browser: 'Chrome 120',
    os: 'Windows 11',
    trafficSource: 'Direct',
    submissionTime: '11:45 AM KST'
  },
  {
    id: 't5',
    name: 'Olivia Martinez',
    company: 'Digital Media ES',
    role: 'Product Manager',
    rating: 4,
    preview: 'Great experience working with this developer. The mobile app he structured was modular and highly responsive across devices.',
    country: 'Spain',
    date: 'Jan 11, 2024',
    status: 'pending',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    email: 'olivia@digitalmedia.es',
    city: 'Madrid',
    submittedFrom: 'Testimonials Page',
    device: 'Mobile',
    browser: 'Safari Mobile',
    os: 'iOS 17',
    trafficSource: 'Google Search',
    submissionTime: '6:30 PM CET'
  },
  {
    id: 't6',
    name: 'Priya Sharma',
    company: 'Tech Solutions Ltd.',
    role: 'Engineering Lead',
    rating: 5,
    preview: 'Priya was extremely impressed with the backend architecture and layout integration. Performance is stellar.',
    country: 'India',
    date: 'Jan 10, 2024',
    status: 'approved',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    email: 'priya@techsolutions.co.in',
    city: 'Mumbai',
    submittedFrom: 'Testimonials Page',
    device: 'Desktop',
    browser: 'Firefox 121',
    os: 'Windows 11',
    trafficSource: 'LinkedIn',
    submissionTime: '3:20 PM IST'
  },
  {
    id: 't7',
    name: 'Lars Andersen',
    company: 'Nordic Design',
    role: 'Design Director',
    rating: 3,
    preview: 'Good work overall. The design system was well structured but the integration details had some minor deviations from spec.',
    country: 'Denmark',
    date: 'Jan 9, 2024',
    status: 'rejected',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    email: 'lars@nordicdesign.dk',
    city: 'Copenhagen',
    submittedFrom: 'Testimonials Page',
    device: 'Desktop',
    browser: 'Chrome 120',
    os: 'macOS Sonoma',
    trafficSource: 'Direct',
    submissionTime: '9:15 AM CET'
  }
];

export const MOCK_SUMMARY = {
  total: 47,
  pending: 8,
  approved: 35,
  rejected: 4,
  trends: {
    total: '+3',
    pending: '+2',
    approved: '+1',
    rejected: '0'
  }
};
